[package]
name = "postgres-derive"
version = "0.1.0"
authors = ["Steven Fackler <sfackler@palantir.com>"]

[lib]
rustc-macro = true
test = false

[dependencies]
postgres-derive-codegen2 = { path = "../postgres-derive-codegen2" }
